site_name: Digital Folklore and Culture
site_url: https://digitalfolklore.net
# repo_url: https://github.com/johnlaudun/digital-folklore
site_author: John Laudun
copyright: 2020, John Laudun, CC BY-NC-SA 4.0

nav:
    - About the Course: Welcome.md
    - 1. What is Folklore?: 01-Folklore.md
    - 2. What is Digital?: 02-Digital.md

theme:
    name: readthedocs

extra:
    version: 1.2

markdown_extensions:
    - smarty