site_name: Digital Folklore and Culture
site_url: https://digitalfolklore.net
# repo_url: https://github.com/johnlaudun/digital-folklore
site_author: John Laudun
copyright: 2020, John Laudun, CC BY-NC-SA 4.0

nav:
    - 1. About the Course: 01-Welcome.md
    - 2. What is Folklore?: 02-Folklore.md
    - 3. What is Digital?: 03-Digital.md

theme:
    name: readthedocs

extra:
    version: 1.2

markdown_extensions:
    - smarty